CREATE DATABASE IF NOT EXISTS db4ai;
USE db4ai;
CREATE TABLE IF NOT EXISTS file_metadata (
    id CHAR(64) PRIMARY KEY, 
    filename VARCHAR(255) NOT NULL,
    uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
